morning_greetings = [
        "Good morning, sir. The weather is lovely today.",
        "Good morning, sir. I trust you slept well?",
        "Rise and shine, sir! Another day, another opportunity.",
        "Good morning, sir. Shall I prepare your breakfast?",
        "Morning, sir. Your schedule for the day is all set.",
        "Good morning, sir. Your coffee is ready.",
        "Morning, sir. Ready to take on the world?",
        "Good morning, sir. Your morning briefing is awaiting your attention.",
        "Morning, sir. The world is yours to conquer.",
        "Good morning, sir. What's on the agenda today?",
        "Good morning, sir. The early bird catches the worm.",
        "Good morning, sir. Your positive attitude brightens the day.",
        "Good morning, sir. Wishing you a day filled with success.",
        "Good morning, sir. Every sunrise brings new opportunities.",
        "Good morning, sir. Your dedication inspires us all.",
        "Good morning, sir. May your day be as amazing as you are.",
        "Good morning, sir. Embrace the possibilities of today.",
        "Good morning, sir. Time to make your mark on the world.",
        "Good morning, sir. Your energy is contagious.",
        "Good morning, sir. Let's make today unforgettable.",
        "Good morning, sir. Your perseverance knows no bounds.",
        "Good morning, sir. You're destined for greatness.",
        "Good morning, sir. Seize the day with confidence.",
        "Good morning, sir. The world awaits your brilliance.",
        "Good morning, sir. Your potential is limitless.",
        "Good morning, sir. Believe in yourself and your dreams.",
        "Good morning, sir. Make today count.",
        "Good morning, sir. May your day be filled with joy and success.",
        "Good morning, sir. Keep shining bright.",
        "Good morning, sir. Today is a blank canvas. Paint it well.",
        "Good morning, sir. Your efforts will lead to triumph.",
        "Good morning, sir. Let your positivity light up the world.",
        "Good morning, sir. Success begins with a smile.",
        "Good morning, sir. Embrace the challenges that lie ahead.",
        "Good morning, sir. Your passion fuels your journey.",
        "Good morning, sir. Start each day with a grateful heart.",
        "Good morning, sir. Your determination is unwavering.",
        "Good morning, sir. Make today better than yesterday.",
        "Good morning, sir. Your actions speak louder than words.",
        "Good morning, sir. Carpe diem - seize the day!",
        "Good morning, sir. Today's potential is limitless.",
        "Good morning, sir. Your vision will shape the future.",
        "Good morning, sir. Success is within your reach.",
        "Good morning, sir. Shine bright like the morning sun.",
        "Good morning, sir. Believe in yourself and your abilities.",
        "Good morning, sir. Wake up and be awesome!",
        "Good morning, sir. Your journey to success starts now.",
        "Good morning, sir. The world is ready for your greatness.",
    ]
afternoon_greetings = [
        "Good afternoon, sir. How's your day progressing?",
        "Afternoon, sir. Lunchtime approaches. Hungry?",
        "Hello, sir. Time flies. Already afternoon!",
        "Good afternoon, sir. Anything I can assist you with?",
        "Afternoon, sir. The world awaits your next move.",
        "Hello, sir. Ready for a productive afternoon?",
        "Good afternoon, sir. Remember to stay hydrated.",
        "Afternoon, sir. Your resilience is admirable.",
        "Hello, sir. Make the most of the day ahead.",
        "Good afternoon, sir. The world is full of possibilities.",
        "Good afternoon, sir. Keep up the great work!",
        "Good afternoon, sir. Your dedication is inspiring.",
        "Good afternoon, sir. The afternoon sun brings new energy.",
        "Good afternoon, sir. Your focus will lead to success.",
        "Good afternoon, sir. Make every moment count.",
        "Good afternoon, sir. Your commitment sets you apart.",
        "Good afternoon, sir. Your efforts are paying off.",
        "Good afternoon, sir. Keep pushing towards your goals.",
        "Good afternoon, sir. The world is yours to explore.",
        "Good afternoon, sir. Stay motivated and determined.",
        "Good afternoon, sir. Your positivity is contagious.",
        "Good afternoon, sir. Embrace the challenges of the day.",
        "Good afternoon, sir. Every step forward is progress.",
        "Good afternoon, sir. Seize the opportunities around you.",
        "Good afternoon, sir. Your hard work is appreciated.",
        "Good afternoon, sir. Make today remarkable.",
        "Good afternoon, sir. Your perseverance is commendable.",
        "Good afternoon, sir. Take a moment to celebrate your achievements.",
        "Good afternoon, sir. Your creativity knows no bounds.",
        "Good afternoon, sir. Trust in your abilities.",
        "Good afternoon, sir. Success is within your reach.",
        "Good afternoon, sir. Your determination will lead to triumph.",
        "Good afternoon, sir. Keep moving forward with confidence.",
        "Good afternoon, sir. Embrace the journey ahead.",
        "Good afternoon, sir. Your resilience will overcome any obstacle.",
        "Good afternoon, sir. Your positive attitude shines through.",
        "Good afternoon, sir. Every challenge is an opportunity for growth.",
        "Good afternoon, sir. Your passion fuels your success.",
        "Good afternoon, sir. Make the most of every moment.",
        "Good afternoon, sir. Your impact on the world is profound.",
        "Good afternoon, sir. Let your brilliance illuminate the path.",
        "Good afternoon, sir. Stay focused on your goals.",
        "Good afternoon, sir. The best is yet to come.",
        "Good afternoon, sir. Your dedication inspires those around you.",
        "Good afternoon, sir. Keep striving for excellence.",
        "Good afternoon, sir. Today is another step towards greatness.",
        "Good afternoon, sir. Your journey to success continues.",
    ]

evening_greetings = [
        "Good evening, sir. Reflecting on the day's achievements?",
        "Evening, sir. Time to unwind and relax.",
        "Hello, sir. Ready to recharge for tomorrow?",
        "Good evening, sir. Dinner is served whenever you're ready.",
        "Evening, sir. Your presence illuminates even the darkest night.",
        "Hello, sir. Shall I prepare the evening agenda?",
        "Good evening, sir. A day well spent is a day to celebrate.",
        "Evening, sir. Your perseverance inspires us all.",
        "Hello, sir. Your insight shapes the world around us.",
        "Good evening, sir. How was your day?",
        "Good evening, sir. Reflect on what went well today.",
        "Good evening, sir. May your evening be as peaceful as a calm sea.",
        "Good evening, sir. Your accomplishments today are commendable.",
        "Good evening, sir. Your hard work deserves recognition.",
        "Good evening, sir. Take a moment to appreciate the beauty of the night sky.",
        "Good evening, sir. Your dedication is truly remarkable.",
        "Good evening, sir. Relax and enjoy the tranquility of the evening.",
        "Good evening, sir. Cherish the moments of serenity.",
        "Good evening, sir. Your resilience in the face of challenges is admirable.",
        "Good evening, sir. Reflect on the lessons learned today.",
        "Good evening, sir. Your kindness brightens the lives of those around you.",
        "Good evening, sir. Find joy in the simple pleasures of the evening.",
        "Good evening, sir. Your accomplishments bring joy to those who admire you.",
        "Good evening, sir. Take pride in how far you've come.",
        "Good evening, sir. Embrace the peace and quiet of the night.",
        "Good evening, sir. Let go of any worries and embrace relaxation.",
        "Good evening, sir. Your strength and determination are truly inspiring.",
        "Good evening, sir. Bask in the warmth of your achievements.",
        "Good evening, sir. Find comfort in the embrace of the evening.",
        "Good evening, sir. Your perseverance lights the way forward.",
        "Good evening, sir. Reflect on the blessings of the day.",
        "Good evening, sir. Your wisdom guides us through life's challenges.",
        "Good evening, sir. Your presence brings joy to those around you.",
        "Good evening, sir. May your dreams be as beautiful as the night sky.",
        "Good evening, sir. Take a moment to appreciate the stillness of the night.",
        "Good evening, sir. Your accomplishments shine brightly, even in the dark.",
        "Good evening, sir. Find solace in the peace of the night.",
        "Good evening, sir. Let the quiet of the evening soothe your soul.",
        "Good evening, sir. Your strength is a beacon of hope for us all.",
        "Good evening, sir. Reflect on the blessings that fill your life.",
        "Good evening, sir. Your kindness brings light to even the darkest nights.",
        "Good evening, sir. Find joy in the beauty of the night.",
        "Good evening, sir. Your determination lights the path to success.",
        "Good evening, sir. May your dreams be filled with happiness and peace.",
        "Good evening, sir. Take a moment to appreciate the wonders of the night.",
        "Good evening, sir. Your accomplishments shine like stars in the sky.",
    ]
goodnight_greetings = [
    "Sir ,Rest well,and let your dreams weave the tapestry of tomorrow.",
    "Sir ,May your sleep be as peaceful as a gentle breeze on a summer night.",
    "Sir ,As the stars sprinkle the night sky, may your dreams be as bright.",
    "Sir ,Wishing you a night filled with the sweetest dreams and the deepest sleep.",
    "Sir ,Let the night wrap you in its comforting embrace, and may you awaken refreshed.",
    "Sir ,Goodnight, sleep tight, and may tomorrow bring you boundless delight.",
    "Sir ,May your dreams be the whispers of angels guiding you to a serene slumber.",
    "Sir ,As the day bids adieu, may your worries fade, and your dreams take flight.",
    "Sir ,Close your eyes and drift away, for tomorrow is a brand new day.",
    "Sir ,May the moonlight kiss your eyelids and usher you into a world of tranquility.",
    "Sir ,Rest easy, for tonight holds the promise of a new dawn.",
    "Sir ,In the stillness of the night, may you find solace and serenity.",
    "Sir ,May your dreams be a sanctuary of joy and wonder.",
    "Sir ,As the night falls, may your troubles dissolve into the darkness.",
    "Sir ,Embrace the silence of the night, for it whispers secrets of peace.",
    "Sir ,Let your dreams be the stars that guide you through the night.",
    "Sir ,May your sleep be deep and rejuvenating, like a well of eternal youth.",
    "Sir ,Drift into the realm of dreams, where anything is possible.",
    "Sir ,As you close your eyes, may you find rest in the arms of serenity.",
    "Sir ,Goodnight, my dear friend, may your dreams be as radiant as your spirit.",
    "Sir ,May your sleep be filled with the melody of serenity and the harmony of peace.",
    "Sir ,Lay your head upon the pillow of dreams, and let the night embrace you.",
    "Sir ,As the night unfolds its velvet curtain, may your dreams take center stage.",
    "Sir ,Sleep like a baby, wrapped in the warmth of tranquility and love.",
    "Sir ,May the night bestow upon you the gift of deep, restful slumber.",
    "Sir ,In the realm of dreams, may you find the answers you seek.",
    "Sir ,Close your eyes, and let the magic of the night weave its spell.",
    "Sir ,As the day makes way for the night, may your worries drift away like leaves in the wind.",
    "Sir ,May your dreams be the canvas upon which your heart paints its desires.",
    "Sir ,Rest your weary soul, for the night holds the promise of renewal.",
    "Sir ,As the stars twinkle overhead, may your dreams sparkle with delight.",
    "Sir ,May your sleep be as peaceful as a meadow bathed in moonlight.",
    "Sir ,Let the night carry you away on wings of tranquility.",
    "Sir ,In the realm of dreams, may you find sanctuary from the chaos of the world.",
    "Sir ,Wishing you a night filled with the sweetest dreams and the gentlest slumber.",
    "Sir ,As the day fades into night, may your worries fade with it.",
    "Sir ,Sleep peacefully, knowing that tomorrow holds endless possibilities.",
    "Sir ,May your dreams be a symphony of joy and wonder.",
    "Sir ,As the night sky unfolds its splendor, may your dreams be equally magnificent.",
    "Sir ,Drift into the embrace of sleep, and let your worries melt away.",
    "Sir ,Close your eyes, and let the whispers of the night soothe your soul.",
    "Sir ,May your dreams be a reflection of the beauty that resides within you.",
    "Sir ,In the stillness of the night, may you find the peace you seek.",
    "Sir ,As the night descends, may your dreams ascend to new heights of bliss.",
    "Sir ,Rest easy, knowing that you are cherished and loved.",
    "Sir ,May your sleep be as serene as a moonlit lake.",
    "Sir ,Let the night cradle you in its arms, and may your dreams be gentle and kind.",
    "Sir ,As the day fades away, may your dreams illuminate the night.",
    "Sir ,Sleep soundly, knowing that you are surrounded by love and warmth.",
    "Sir ,May the night wrap you in its comforting embrace, and may you awaken to a world renewed.",
    ]
welcomedlg = [
    "Greetings, sir, your presence brightens the day.",
    "Ah, sir, a pleasure to encounter you.",
    "Well met, sir, may your day be filled with brilliance.",
    "Salutations, sir, your company is most welcome.",
    "Good day, sir, your arrival is a delight.",
    "Ahoy, sir, your presence elevates the atmosphere.",
    "Top of the morning to you, sir, may your day be grand.",
    "Hail, sir, your appearance brings cheer.",
    "Howdy, sir, your presence is a boon.",
    "Well hello there, sir, your company is a treasure.",
    "Greetings and salutations, sir, may your day be splendid.",
    "Hey there, sir, your presence is a pleasure.",
    "Greetings, esteemed sir, may your day be filled with success.",
    "Ah, sir, a sight for sore eyes indeed.",
    "Good to see you, sir, your presence is most reassuring.",
    "Greetings, noble sir, may your day be as majestic as you are.",
    "Well met, good sir, your presence is a beacon of positivity.",
    "Ahoy there, sir, may your day be filled with adventure.",
    "Hello, dear sir, your presence is a gift.",
    "Greetings, sir, may your day be as splendid as your presence.",
    "Well hello, sir, your arrival is a delight.",
    "Salutations, sir, your presence brings joy to the heart.",
    "Good day, sir, may your path be strewn with success.",
    "Ah, sir, your presence brings a smile to the face.",
    "Hail, noble sir, may your day be filled with triumph.",
    "Howdy, sir, your presence is a blessing.",
    "Greetings, esteemed sir, may your day be as bright as your presence.",
    "Hey there, sir, your arrival is most fortuitous.",
    "Good to see you, sir, may your day be filled with prosperity.",
    "Greetings, noble sir, your presence is a boon to all.",
    "Well met, good sir, may your day be as magnificent as you are.",
    "Ahoy there, sir, your presence is a ray of sunshine.",
    "Hello, dear sir, may your day be filled with happiness.",
    "Greetings, sir, your presence is a source of inspiration.",
    "Well hello, sir, your arrival is eagerly anticipated.",
    "Salutations, sir, your presence fills the heart with gladness.",
    "Good day, sir, may your day be filled with achievement.",
    "Ah, sir, your presence brings warmth to the soul.",
    "Hail, noble sir, may your day be as illustrious as your presence.",
    "Howdy, sir, your presence is a boon to all who encounter it.",
    "Greetings, esteemed sir, may your day be filled with fulfillment.",
    "Hey there, sir, your presence brings joy to the heart.",
    "Good to see you, sir, may your day be as bright as your smile.",
    "Greetings, noble sir, your presence is a welcome sight indeed.",
    "Well met, good sir, may your day be filled with abundance.",
    "Ahoy there, sir, your presence brings a sense of excitement.",
    "Hello, dear sir, may your day be as delightful as your company.",
    "Greetings, sir, your presence brings a sense of serenity.",
    "Well hello, sir, your arrival heralds good tidings.",
    "Salutations, sir, may your day be filled with joy and laughter.",
    "Delighted to cross paths with you, sir.",
    "It's a pleasure to encounter you, sir.",
    "Thrilled to have you here, sir.",
    "Such a joy to see you, sir.",
    "Your presence is a welcome sight, sir.",
    "You bring brightness wherever you go, sir.",
    "Your arrival is a breath of fresh air, sir.",
    "Seeing you is always a highlight, sir.",
    "Your presence adds a touch of elegance, sir.",
    "You make every gathering better, sir.",
    "Your presence is like a ray of sunshine, sir.",
    "Always a pleasure to have you around, sir.",
    "You bring a sense of warmth, sir.",
    "Your company is truly appreciated, sir.",
    "It's wonderful to have you here, sir.",
    "Your presence elevates the atmosphere, sir.",
    "A joyous sight to behold, sir.",
    "You make any occasion brighter, sir.",
    "Your presence is a true blessing, sir.",
    "You add a touch of class, sir.",
    "Always a delight to see you, sir.",
    "Your presence brings joy to those around you, sir.",
    "You bring a sense of calm, sir.",
    "Your company is always cherished, sir.",
    "You light up the room, sir.",
    "Your presence is a gift, sir.",
    "A pleasure to have you join us, sir.",
    "You bring a sense of harmony, sir.",
    "Your presence is a source of inspiration, sir.",
    "Always a welcome addition, sir.",
    "Your company is truly valued, sir.",
    "You bring a sense of positivity, sir.",
    "Your presence is a ray of hope, sir.",
    "It's a privilege to see you, sir.",
    "You make everything better, sir.",
    "Your company is like a beacon, sir.",
    "Always a pleasure to have you around, sir.",
    "Your presence brings a smile to everyone's face, sir.",
    "You bring a sense of energy, sir.",
    "Your company is a true delight, sir.",
    "It's wonderful to have you here with us, sir.",
    "Your presence adds a touch of magic, sir.",
    "A true pleasure to see you, sir.",
    "Your company is like a breath of fresh air, sir.",
    "You bring a sense of grace, sir.",
    "Your presence is truly uplifting, sir.",
    "Always a joy to have you around, sir.",
    "Your company is a gift to us all, sir.",
    "It's an honor to see you, sir.",
    "Your presence enriches every moment, sir.",
]